-- 1) public.bands
CREATE TABLE public.bands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  name character varying UNIQUE
);

-- 2) public.actors
CREATE TABLE public.actors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  is_guest boolean,
  user_id uuid UNIQUE DEFAULT gen_random_uuid(),
  display_name character varying
);
-- FK: actors.user_id -> auth.users.id
ALTER TABLE public.actors
  ADD CONSTRAINT actors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- 3) public.guests
CREATE TABLE public.guests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  display_name character varying
);

-- 4) public.period_times
CREATE TABLE public.period_times (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time time,
  end_time time
);

-- 5) public.votes
CREATE TABLE public.votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  date date,
  period_id bigint,
  actor_id bigint,
  is_active boolean DEFAULT true
);
-- FK: votes.period_id -> period_times.id
ALTER TABLE public.votes
  ADD CONSTRAINT votes_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.period_times(id);
-- FK: votes.actor_id -> actors.id
ALTER TABLE public.votes
  ADD CONSTRAINT votes_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);

-- 6) public.decided_periods
CREATE TABLE public.decided_periods (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  is_active boolean DEFAULT true,
  date date,
  period_id bigint
);
-- FK: decided_periods.period_id -> period_times.id
ALTER TABLE public.decided_periods
  ADD CONSTRAINT decided_periods_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.period_times(id);

-- 7) public."band-members"
CREATE TABLE public."band-members" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now(),
  actor_id bigint,
  band_id bigint,
  is_active boolean DEFAULT true
);
-- FK: band-members.band_id -> bands.id
ALTER TABLE public."band-members"
  ADD CONSTRAINT band_members_band_id_fkey FOREIGN KEY (band_id) REFERENCES public.bands(id);
-- FK: band-members.actor_id -> actors.id
ALTER TABLE public."band-members"
  ADD CONSTRAINT band_members_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actors(id);